fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    python: "git://github.com/stankevich/puppet-python.git"
    epel: "git://github.com/stahnma/puppet-module-epel.git"
  symlinks:
    puppetboard: "#{source_dir}"
